//Todos os includes dos modulos
#include <stdbool.h>
#include "digitar.h"
#include "validacao.h"
#include "struct.h"
#include "../MENUS/menus_horario.h"
#include "../MENUS/menus_clientes.h"
#include "../MENUS/menus_precos.h"
#include "../MENUS/menus_maquinas.h"
#include "../MENUS/menus.h"
#include "../MENUS/LISTA/listar.h"

#define RED   "\x1B[31m"
#define GRN   "\x1B[32m"
#define YEL   "\x1B[33m"
#define BLU   "\x1B[34m"
#define MAG   "\x1B[35m"
#define CYN   "\x1B[36m"
#define WHT   "\x1B[37m"
#define RESET "\x1B[0m"
